# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' #do not deploy on pull request

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:

          host: ${{secrets.PROD_SSH_HOST}}

          username: ${{ secrets.PROD_SSH_USERNAME }}

          password: ${{ secrets.PROD_SSH_PASSWORD }}

          command_timeout: 20m

          script: |
            cd ${{ secrets.PROD_APP_DIR }}
            git remote set-url origin git@github.com:Movam/test-repo.git
            git checkout -f
            git pull origin main
            
    
